"""user datetime default value added

Revision ID: 17617468767c
Revises: 416bafc97ff3
Create Date: 2023-06-15 11:21:49.142681

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '17617468767c'
down_revision = '416bafc97ff3'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
