"""item type issue fix

Revision ID: b0c3cc000e60
Revises: dde5e86a3d8c
Create Date: 2023-07-05 06:33:18.197263

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'b0c3cc000e60'
down_revision = 'dde5e86a3d8c'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
