"""user item relationship added

Revision ID: dd2aa6a10321
Revises: b025c3a259ba
Create Date: 2023-06-16 12:01:59.378444

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'dd2aa6a10321'
down_revision = 'b025c3a259ba'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('items', sa.Column('owner_id', sa.Integer(), nullable=True))
    op.create_foreign_key(None, 'items', 'users', ['owner_id'], ['id'])
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'items', type_='foreignkey')
    op.drop_column('items', 'owner_id')
    # ### end Alembic commands ###
