# Using another file prod-secret.yaml for secrets used in production.
apiVersion: v1
kind: Secret
metadata:
  name: app-secret
type: Opaque
data:
  # SQLALCHEMY_DATABASE_URL: postgresql://postgres:tiger@postgres-service.default/test_db
  SQLALCHEMY_DATABASE_URL: cG9zdGdyZXNxbDovL3Bvc3RncmVzOnRpZ2VyQHBvc3RncmVzLXNlcnZpY2UuZGVmYXVsdC90ZXN0X2Ri
---
apiVersion: v1
kind: Secret
metadata:
  name: postgres-secret
type: Opaque
data:
  # SECRET_KEY: 09d25e094faa6ca2556c818166b7a9563b93f7099f6f0f4caa6cf63b88e8d3e7
  SECRET_KEY: MDlkMjVlMDk0ZmFhNmNhMjU1NmM4MTgxNjZiN2E5NTYzYjkzZjcwOTlmNmYwZjRjYWE2Y2Y2M2I4OGU4ZDNlNw==
  # ALGORITHM: HS256
  ALGORITHM: SFMyNTY=
  # ACCESS_TOKEN_EXPIRE_MINUTES: 30
  ACCESS_TOKEN_EXPIRE_MINUTES: MzA=
  # POSTGRES_DB: test_db
  POSTGRES_DB: dGVzdF9kYg==
  # POSTGRES_PASSWORD: tiger
  POSTGRES_PASSWORD: dGlnZXI=