apiVersion: v1
kind: Secret
metadata:
  name: app-secret
type: Opaque
data:
  # SQLALCHEMY_DATABASE_URL: postgresql://postgres:tiger@postgres-service.default/test_db
  SQLALCHEMY_DATABASE_URL: cG9zdGdyZXNxbDovL3Bvc3RncmVzOnRpZ2VyQHBvc3RncmVzLXNlcnZpY2UuZGVmYXVsdC90ZXN0X2Ri
---
apiVersion: v1
kind: Secret
metadata:
  name: postgres-secret
type: Opaque
data:
  # POSTGRES_DB: test_db
  POSTGRES_DB: dGVzdF9kYg==
  # POSTGRES_PASSWORD: tiger
  POSTGRES_PASSWORD: dGlnZXI=