apiVersion: v1
kind: Service
metadata:
  name: testapp-service
spec:
  type: LoadBalancer
  selector:
    app: testapp
  ports:
    - protocol: TCP
      port: 8000
      targetPort: 8000
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: testapp-deployment
  labels:
    app: testapp
spec:
  replicas: 1
  selector:
    matchLabels:
      app: testapp
  template:
    metadata:
      labels:
        app: testapp
    spec:
      containers:
      - name: testapp
        image: shubhadip45/fastapi-test-app:latest
        command: ["/bin/bash", "-c", "alembic upgrade head && uvicorn test_app.main:app --host 0.0.0.0 --port 8000 --reload"]
        env:
          - name: SECRET_KEY
            valueFrom:
              secretKeyRef:
                name: app-secret
                key: SECRET_KEY
          - name: ALGORITHM
            valueFrom:
              secretKeyRef:
                name: app-secret
                key: ALGORITHM
          - name: ACCESS_TOKEN_EXPIRE_MINUTES
            valueFrom:
              secretKeyRef:
                name: app-secret
                key: ACCESS_TOKEN_EXPIRE_MINUTES
          - name: SQLALCHEMY_DATABASE_URL
            valueFrom:
              secretKeyRef:
                name: app-secret
                key: SQLALCHEMY_DATABASE_URL